### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by dh4** [comment]
Awesome! Thanks for this!

Could you verify everything looks good with the latest commit I pushed? Is "русский язык" the correct way to put it in the languages drop down? Thanks!

**Comment by TotalCaesar659** [comment]
> Is "русский язык" the correct way to put it in the languages drop down?

It's enough just to write "Русский" there.

> Could you verify everything looks good with the latest commit I pushed?

There are some untranslatable strings:
1) Disclaimer in the main window (BTW, it has grey color that is barely visible on light background)

2) Buttons "Cancel" and "OK".

**Comment by dh4** [comment]
Thanks! I've made those strings translatable. Let me know if you find any others that are missing.

**Comment by TotalCaesar659** [comment]
Updated Russian translation [here](https://github.com/dh4/mupen64plus-qt/pull/41).
1) Here is the differnce in translatable strings between table and list.


2) Please change the font color here to black, it's hard to read this.

**Comment by dh4** [comment]
I've fixed these with the latest commit. Thanks!

**Comment by TotalCaesar659** [comment]
One last mini bug: there is no space in updated (https://github.com/dh4/mupen64plus-qt/blob/ab99b88e0b2b753d7bdb77237c48ed47161025a6/resources/locale/mupen64plus-qt_ru.ts#L119) string in Russian (English is alright).

I don't know, is it a bug or I did something wrong (I've compiled newly cloned version with full removing of previous one). Could you check this please?

**Comment by dh4** [comment]
I've fixed that issue. Thanks!

**Pull request merged**
