### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by dh4** [comment]
Thanks for this! I've pushed a commit that makes the hotkey descriptions translatable as well.

I'm going to do some testing in the next couple days and push out a new release with the changes that have been made.

**Comment by TotalCaesar659** [comment]
[Updated](https://github.com/dh4/mupen64plus-qt/pull/45). Let's finish touches: there some untranslatable strings.
Settings->Configure->Graphics->Resolution:

"About" window:

If you need some more updates, tell me, it would be better to add them before new release.

**Comment by dh4** [comment]
Thanks! I've fixed those with the latest commit. Let me know if you find any others. I'll make sure we have everything up to date before pushing a new version.

**Comment by TotalCaesar659** [comment]
[Updated](https://github.com/dh4/mupen64plus-qt/pull/46). I haven't found anything more, so I guess it's time.

**Pull request merged**
