### PR TITLE
Added simple manpage.

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
Debian packaging complains about missing manpage.

### CODE REVIEW

**Comment by dh4** [comment]
Is a manpage really required for Debian? As I understand it, graphical applications with no options that can be passed to them usually don't have manpages.

The manpage would need to be edited slightly. It currently lists the options as if you can pass them to Mupen64Plus-Qt via command line, but those options are only for the Mupen64Plus executable. (i.e. running `mupen64plus-qt --fullscreen` would do nothing).

**Comment by sergiobenrocha2** [comment]
Every executable must have a manpage.

**Comment by sergiobenrocha2** [comment]
So there aren't any option to pass for it?

**Comment by dh4** [comment]
Those options are what the launcher passes when it launches Mupen64Plus in another process. They aren't passed to Mupen64Plus-Qt directly (I should make this clearer in the README).

You can launch a ROM and then run the command `ps aux | grep mupen64plus` to see what parameters the launcher passed to the Mupen64Plus process.

**Comment by sergiobenrocha2** [comment]
I'll update it

**Comment by sergiobenrocha2** [comment]
Fixed.

**Comment by dh4** [comment]
Merged. Thanks

**Pull request merged**
