### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by dh4** [comment]
Thanks!

Not sure if you're interested, but I ported the Russian translation to CEN64-Qt as well:
https://github.com/dh4/cen64-qt/blob/master/resources/locale/cen64-qt_ru.ts

**Comment by TotalCaesar659** [comment]
Updated Russian translation [there](https://github.com/dh4/cen64-qt/pull/11).
BTW, please, re-check the translation, program doesn't want to catch newly translated strings even after merging like [before](https://github.com/dh4/mupen64plus-qt/pull/40#issuecomment-531527956).

**Comment by dh4** [comment]
It's fixed now. The .qm file needed to be updated.

For reference, those can be updated with the following two commands in the base directory:
```
lupdate mupen64plus-qt.pro
lrelease mupen64plus-qt.pro
```

**Comment by TotalCaesar659** [comment]
Ah, thanks, I just used to translate programs on GTK just by one PO file.

**Pull request merged**
